site_name: IHC 2019.2
site_description: Repositório da disciplina de IHC 2019.2
repo_url: https://github.com/Interacao-Humano-Computador/2019.2-Wish
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/Interacao-Humano-Computador/2019.2-Wish">IHC 2019.2</a>.
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: assets/img/logo.png
  favicon: favicon.ico
  palette:
    primary: 'white'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Interacao-Humano-Computador/2019.2-Wish'

plugins:
  - search

extra_css:
  - assets/css/extra.css

pages:
  - Home: 'index.md'
  - Escolha do site & processo de design: 'sprint01/escolha.md'
  - Guia de Estilo: 'sprint01/guia.md'
  - Heurísticas: 'sprint01/heuristicas.md'
  - Storyboard: 'sprint01/storyboard.md'
  - Metas de Usabilidade: 'sprint01/metas.md'
  - RichPicture: 'sprint01/rich.md'
  - Análise de Tarefas: 'sprint01/analise.md'
  - Características da Plataforma: 'sprint01/caracteristicas-plataforma.md'
  - Requisitos elicitados: 'sprint01/requisitos.md'
  - Princípios do Projeto: 'sprint01/Principios_Projeto.md'
  - Perfil do usuário:
    - Instrospecção: 'sprint01/introspeccao.md'
    - Perfil de usuário: 'sprint01/perfil.md'
    - Questionário: 'sprint01/questionario.md'
  - Protótipo de alta fidelidade: 'sprint01/prototipo_alta.md'
  - Análise Google Lighthouse: 'sprint01/lighthouse.md'